#!/bin/sh

WINDOW_ID="$1"
NUMBER_OF_SCREENS="$2"
SCREEN_WIDTH="$3"
SCREEN_HEIGHT="$4"

GRAVITY="0"
X="0"
Y="0"

WIDTH=$(($SCREEN_WIDTH/($NUMBER_OF_SCREENS*2)))
HEIGHT="-1"

# we need to remove the maximized_horz attribute in case the window was maximized with hit_top before
wmctrl -i -r "$WINDOW_ID" -b remove,maximized_horz

# maximize it vertically via EWMH so padding (taskbar for example) is respected
wmctrl -i -r "$WINDOW_ID" -b add,maximized_vert 

# change position and size of the window
wmctrl -i -r "$WINDOW_ID" -e $GRAVITY,$X,$Y,$WIDTH,$HEIGHT
